apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: nada
  name: nada-soda
  namespace: nada
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      external:
        - host: slack.com
    inbound:
      rules:
        - application: '*'
          namespace: '*'
  replicas:
    min: 1
    max: 2
  env:
    - name: BIGQUERY_DATASET
      value: soda
    - name: BIGQUERY_TABLE
      value: historic
  envFrom:
    - secret: slack-token
  gcp:
    bigQueryDatasets:
      - name: soda
        permission: READWRITE
