apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: nada
  name: nada-soda
  namespace: nada
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      external:
        - host: slack.com
        - host: hooks.slack.com
        - ipv4: 18.134.215.41
        - ipv4: 18.159.197.225
        - ipv4: 18.168.172.238
        - ipv4: 18.169.120.191
        - ipv4: 18.169.61.189
        - ipv4: 3.68.124.168
        - ipv4: 3.68.124.95
        - ipv4: 3.68.170.153
        - ipv4: 3.68.175.98
        - ipv4: 52.29.238.212
    inbound:
      rules:
        - application: '*'
          namespace: '*'
  replicas:
    min: 1
    max: 2
  env:
    - name: BIGQUERY_DATASET
      value: soda
    - name: BIGQUERY_TABLE
      value: historic
  envFrom:
    - secret: slack-token
  gcp:
    bigQueryDatasets:
      - name: soda
        permission: READWRITE
